### ISSUE TITLE
Readme says open .sketchplugin file -- none exists

### ISSUE THREAD

**Issue by yuchant** [Shopify/polaris-telescope#6]
The readme says to download & open a .sketchplugin file but no such file exists.

Are we supposed to build it ourselves?

If I try to `npm install` I get an error enabling sketch developer mode.

Either way can you update the docs with expected procedure? 

```
[1/1] 🔗  Symlinking the plugin polaris-telescope...
success Plugin polaris-telescope symlinked
polaris-telescope - 0.9.4
error Error while enabling the Sketch developer mode.
```

Thank you! Looks great.

**Comment by yuchant** [comment]
I'm being an idiot. I see the file now.

**Comment by kaelig** [comment]
Hey @yuchant, thanks for using Polaris Telescope!

I'll close this if that's okay, but let us know if you have any questions.
