### ISSUE TITLE
lack of  .sketchplugin file 

### ISSUE THREAD

**Issue by MarcSteven** [Shopify/polaris-telescope#9]
Perhaps you forget to add this file into the folder

**Comment by MarcSteven** [comment]
https://polaris.shopify.com/resources/polaris-telescope it's here ,so you should add this file in the project !!!

**Comment by kaelig** [comment]
Install instructions are in the README, and can also be found in the [GitHub releases](https://github.com/Shopify/polaris-telescope/releases) for this project.

Feel free to open a pull request if this isn't clear enough.

**Comment by MarcSteven** [comment]
ok @kaelig

**Comment by vfonic** [comment]
I also couldn't find the `.sketchplugin` file in the downloaded "Source code". I think the file name is really confusing:

> To install: download this file, unzip and double click on the .sketchplugin

You could add this to the release notes, right above.

**Comment by kaelig** [comment]
Thank you for the feedback! 

The file name is generated by the skpm publish script — sorry it's confusing! You may open an issue at https://github.com/skpm/skpm/issues

**Comment by vfonic** [comment]
I see. I won't be opening the issue, but feel free to open one if you want.

Thanks,
Viktor

**Comment by kaelig** [comment]
Fair enough! Note that the preferred way to download Polaris Telescope is via the download link on this page: https://polaris.shopify.com/resources/polaris-telescope
